remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Jhoan Andres Monsalve Garcia
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/jhoan-50067.appspot.com/o/WhatsApp%20Image%202023-09-29%20at%205.40.31%20PM.jpeg?alt=media&token=c91c50b7-e439-4f3a-9bd4-d8915ec32917
          

